### ISSUE TITLE
Our definition of crop is ...? And check for crops ...

### ISSUE THREAD

**Issue by FrederikBaumgarten** [lizzieinvancouver/egret#12]
@dbuona: What is the definition of crop species that we decided to exclude from the paper selection? Walnut are cultivated in different varieties, would that make them a crop for example?

@mention-group/all: are there any exclusion criteria missing in the current method version
 [method](https://github.com/lizzieinvancouver/egret/blob/main/docs/methods.pdf)

**Comment by dbuona** [comment]
I am not sure how this was determined. I think maybe the purpose of this was to exclude corn and soybeans etc. I think we should discuss what to do about fruit and nut trees.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan I suspect you have some info on this.... which maybe could bring us close to closing this.

**Comment by lizzieinvancouver** [comment]
[This file --oegres_fullsearch.xlsx](https://github.com/lizzieinvancouver/egret/blob/main/data/oegres_fullsearch.xlsx) has a column called crops, which has a C for things we considered a crop, but I cannot figure out if we excluded those papers and a quick glance through [this file -- egret_fullsearch.xlsx](https://github.com/lizzieinvancouver/egret/blob/main/data/egret_fullsearch.xlsx) suggests some of the species flagged in the oegres file may have been scraped so it would be good if someone could take over:

- [ ] checking whether papers flagged as crops in [oegres_fullsearch.xlsx](https://github.com/lizzieinvancouver/egret/blob/main/data/oegres_fullsearch.xlsx) were scraped
- [ ] propose a plan to discard species as crops... (I checked ospree and I think we just discarded super obvious crops like Vitis viniferia and Malus domestica and kiwi)

**Comment by dbuona** [comment]
As long as we are okay with Hazelnut and Walnut, I think we are good here. I was defining crops in my brains as something that has been domesticated from a wild ancestor (i.e. Malus domestica) as opposed to cultivars of wild type species (ie Corylus avellana). I will assume all are okay with this and close the issue
