### ISSUE TITLE
try new OCR thing

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#16]
@buniwuuu If you need a task this week, I had a colleague suggest an OCR for graphs link:

https://apps.automeris.io/wpd/

Could you follow the tutorial and report back on how it might work for us? For example, you could try any figure from this paper that I am behind on scraping:

[Ikeda_2001.pdf](https://github.com/lizzieinvancouver/egret/files/14003854/Ikeda_2001.pdf)

**Comment by buniwuuu** [comment]
Hi @lizzieinvancouver,

I tried scraping Figure 1, 2, and 3. I think it works pretty well! The calibration is easier than Fiji, and you can add different datasets (Figure 3) and have them all in one CSV file. 
For error bars, we would have to digitize them separately and subtract them later like how we did using Fiji. 
An advantage of using this OCR is that we will be able to digitize continuous data using the automatic mode. 

Attached are the values I scraped. 

[Ikeda2001_3.csv](https://github.com/lizzieinvancouver/egret/files/14071115/Ikeda2001_3.csv)
[Ikeda2001_2.csv](https://github.com/lizzieinvancouver/egret/files/14071116/Ikeda2001_2.csv)
[Ikeda2001_1.csv](https://github.com/lizzieinvancouver/egret/files/14071139/Ikeda2001_1.csv)

**Comment by lizzieinvancouver** [comment]
@buniwuuu Wow! This sounds exciting. Let's discuss next time we have an EGRET meeting in lab meeting whether we should switch to this.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Did Ikeada2001 get entered in the end?

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver thanks for following up on this! No, it appears it was not.

@buniwuuu are you able to add this data to your egret_BW data file?

**Comment by DeirdreLoughnan** [comment]
Thanks @buniwuuu for adding the data!
