### ISSUE TITLE
check for species we have OSPREE data on 

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#2]
@sophiacc01 review what species we have data for compared to OSPREE, then do some searches to compare what’s missing (e.g. ISI search ‘picea abies AND germination’)

[Here's a species list to start with](https://github.com/lizzieinvancouver/ospree/blob/master/analyses/traits/notes/Species.list.trait.csv) 

Please ping me (@lizzieinvancouver) and Dan (@dbuona) with issues and questions.

**Comment by sophiacc01** [comment]
@lizzieinvancouver Hi Lizzie, I just wanted to confirm that I should only look at the species for the papers we decided to keep out of those in the initial search result? (the 181 ones Alina and I marked "Y")

**Comment by lizzieinvancouver** [comment]
@sophiacc01 Yes, start with the ones we have marked as 'Y' ... our goal is to make sure we're not missing key papers (and thus key search terms), so once you look up the species in ISI you'll be looking for relevant studies (ones we could use) that we have not found in any way before.

**Comment by sophiacc01** [comment]
@lizzieinvancouver Hi Lizzie, I've been reviewing the species, and I wanted to check if it would be appropriate to do the following search to find missing articles:
 'species name' AND 'germinat*' AND 'stratif*'
I know you suggested 'species name' AND 'germination', but given that 'germinat*' and 'stratif*' were the initial terms that Alina and I used I thought they might yield more appropriate and refined results. But if it is better to keep the term more general so that there's less chance we miss a paper I can definitely do that instead.

**Comment by lizzieinvancouver** [comment]
@sophiacc01 As the goal is to find papers we may have missed we don't want to repeat too many of our earlier search terms.  But we also can't have crazy high numbers of papers. Could you do 'species name' AND 'germinat*' and record the number of ISI results for each to start and report back that info? If easy, you might add a column with paper number for 'species name' AND 'germinat*' AND 'stratif*' Thanks!

**Comment by sophiacc01** [comment]
@lizzieinvancouver Sounds good! Here is a sheet with those counts https://docs.google.com/spreadsheets/d/1i7jklTh09EpIWuwRunlnPIqApSXxUiwRhsvKvQdfqGs/edit?usp=sharing

Looks like most of them are a reasonable size to go through but a few are in the hundreds. I can still go through them, just let me know what you think is best. I also made a second sheet on that link ("species counts") which is a list of the variety and number of each species that were present in the papers Alina and I kept, in case that is helpful.

**Comment by lizzieinvancouver** [comment]
@sophiacc01 Thanks! Yes, given our goal I think best to the AND germinat* only (not adding statif*). But let's start with a few and see what we find. The goal is to find out if there are any papers that have the data we want but missed given our previous search terms. Let's do:

- Fagus sylvatica
- Picea abies
- Corylus avellana
- Quercus robur

First and see what you find. (Sorry, I know some of those have a lot.)

**Comment by sophiacc01** [comment]
@lizzieinvancouver Great thanks, I'll get started on that!

**Comment by lizzieinvancouver** [comment]
See issue #31
