### ISSUE TITLE
What is happening on the USDA branch?

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/egret#24]
@selenashew @buniwuuu @ngoj1 @lizzieinvancouver 

Are you currently working on the branch to create new cleaning files or are all files now also copied onto the main branch? 

It appears like there have not been any updates to the branch in a couple of weeks, so I was curious whether you planned to use it moving forward or had plans to merge it back to the main branch?

**Comment by ngoj1** [comment]
I remember the branch was brought up at the last last lab meeting (not the garden visit) but as far as I know all of our commits have been to the main branch, at least as of the time I started working on the germination data cleaning script! Selena probably has a better idea as what will be done with the branch later so I'll let her speak on that, but all of the code I started is in the main folder.

**Comment by lizzieinvancouver** [comment]
@selenashew @ngoj1 @DeirdreLoughnan @buniwuuu Thanks all for your help on this! We usually would rather maintain or merge back in branches so I'd like to think carefully about what to do with this branch, see [here](https://github.com/lizzieinvancouver/egret/commits/data_scraping_branch). @selenashew Can you explain when and why you created this branch?

 And can you figure out which commits are unique to this branch? According to my git log:

```
lizzie@dhcp-206-12-181-216:~/Documents/git/projects/egret$ git log --no-merges data_scraping_branch ^main
commit 83c8eab59f68ec4af4c8de2a8a94db53d5b99229 (origin/data_scraping_branch, data_scraping_branch)
Author: Selena Shew <shewselena@gmail.com>
Date:   Fri Jun 7 19:39:36 2024 -0700

    finished script to count the number of data tables per each type & renamed the file

commit 241276a857db910b0cb078c0b2bd94a87249e1e9
Author: Selena Shew <shewselena@gmail.com>
Date:   Wed Jun 5 19:50:03 2024 -0700

    Updated script to check & rename all relevant data tables; created a new script to return count of relevant data tables


```
But please check yourself and let us know what you know about the branch. Then we can figure out what to do about it. Thank you!

**Comment by selenashew** [comment]
Hi @lizzieinvancouver @DeirdreLoughnan,

As Justin has mentioned, all of our code, edits, files, etc. are all on the main branch now. Originally I was working via the other branch as to have a separate "test playground" in order to play around with my code or move files without making any permanent changes, but after our first summer lab meeting where Deirdre confirmed we can just make direct changes to the main branch, I stopped using the side branch and have pushed all changes to main. I will just delete the other branch that I've created as all of those changes have since been incorporated into the main.

**Comment by lizzieinvancouver** [comment]
@selenashew Okay, but I think better if I delete it as then I can explain it clearly for my future self when looking at that commit.

**Comment by lizzieinvancouver** [comment]
Okay, all set (though I now recall that deleting a branch does not allow commit messages).

> lizzie@dhcp-206-12-181-216:~/Documents/git/projects/egret$ git branch -d data_scraping_branch
> warning: deleting branch 'data_scraping_branch' that has been merged to
>          'refs/remotes/origin/data_scraping_branch', but not yet merged to HEAD.
> Deleted branch data_scraping_branch (was 83c8eab).
> lizzie@dhcp-206-12-181-216:~/Documents/git/projects/egret$ git push
> Everything up-to-date
> lizzie@dhcp-206-12-181-216:~/Documents/git/projects/egret$ git push origin --delete data_scraping_branch
> remote: This repository moved. Please use the new location:
> remote:   git@github.com:lizzieinvancouver/egret.git

This reminds me that we probably should have a document about how we want folks to use git in the lab. We don't have too many branches and usually agree on them but I now realize we have never written this down.
