### ISSUE TITLE
write (or draw) a highly simplified example of what the Baskins recommend to do

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#29]
@christophe-rd Thanks!

**Comment by christophe-rd** [comment]
To determine what temperature regime seeds require, they propose the  **Move along experiment:**

1. Select an appropriate temperature regime (e.g. Spring, Summer, Autumn, Winter), e.g.:
	1. **Early** spring and **early** autumn are the same (15/6 Celsius;12/12h)
	2. **Late** spring and **late** autumn are the same (20/10 Celsius ;12/12h)
	3. Summer regime (25/15 Celsius)
	4. Winter regime (5/1 Celsius)
2. Seeds are kept on a wet substrate
3. Treatments:
	1. Control: kept at each temperature regime until the experiment is finished (4 weeks/temperature regime)
	2. Start at summer temperature (12 weeks) 
		a. moved along to the other temperature regimes
	3. Start at winter temperature (12 weeks)
		a. moved along to the other temperature regimes

**Comment by lizzieinvancouver** [comment]
@dbuona Is this what you were thinking of? Please reply, thanks.

**Comment by lizzieinvancouver** [comment]
@christophe-rd @dbuona  [Move Along](https://www.youtube.com/watch?v=XleOkGsYgO8) .. also, I am not a big Coldplay fan, but if you have not watched the Glastonbury footage of Coldplay with Michael J Fox, it's pretty good.

**Comment by lizzieinvancouver** [comment]
@christophe-rd Seems to have done this, so I am closing it. Thanks all!
