### ISSUE TITLE
finalize info on reviewing papers to include or exclude

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#3]
Okay, I moved stuff other than the PDFs here ... just for consistency with how we did it with OSPREE and for safety.

I also did a few entries ... so now back to you guys to try. Here are the instructions:

We're filling in the oegres_fullsearch file, but on Google Drive so we don't duplicate efforts: https://drive.google.com/drive/folders/1vfD6LDYfLU_bXT1duVkKw1l-g7eEnK97?usp=sharing

Going through abstracts in savedrecs_part1.txt and savedrecs_part2.txt (in repo and Drive). If you need to pull a paper that is an 'A' (for accept) for any reason, drop it in the OEGRES papers folder in the drive. 

Review the meta tab before doing any entry. 

Add info to metadata tab (or OEGRES_searchnotes.txt in the repo if you think better) on info we want people doing data entry to share. @dbuona I moved some of your notes that might be useful when doing the reviewing into _README.txt in the repo, so please move as needed.

**Comment by dbuona** [comment]
I just did 10 entries. It seemed pretty straightforward, I don't have much to add and didn't encounter any additional criteria for rejection.

**Comment by DeirdreLoughnan** [comment]
I did ten as well. One of the papers I reviewed was looking at the effects of a fungi on seed germination, which I considered a reason to reject it.

**Comment by DeirdreLoughnan** [comment]
I checked the 10 entries that Grace did and her entries seemed correct. 

One abstract read like a review paper though. I assume that we would still pull it and check, but ultimately not include any paper that doesn't include novel data to prevent us from potentially duplicating data, right?

**Comment by lizzieinvancouver** [comment]
This seems super done ...
