### ISSUE TITLE
clean out the cleaning folder and finalize the source file for now

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#49]

**Comment by lizzieinvancouver** [comment]
Leaving this open until all files are sourced (cleanMisc.R is missing) but otherwise I think @DeirdreLoughnan can close this when she thinks we're good.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I think this is done. cleanMisc.R is now sourced in cleanAll.R

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan The source file now starts with 2X more rows ...

```
> # 1. Get the data (reads in a dataframe called `egret')
> source("cleaning/source/mergedata.R") # 30766 rows, 45 columns
> 
> dim(d)
[1] 61839    45
```

And then half get deleted here in cleanDatasetID:

```
> dim(d)
[1] 61839    45
> d <- subset(d, datasetID !="al-absi10" | entered.by != "TA")
> 
> dim(d)
[1] 31110    45
```

Do you think this code is supposed to be `&` instead of` | `?

```
d <- subset(d, datasetID !="al-absi10" | entered.by != "TA")
d <- subset(d, datasetID !="chen06" | entered.by != "AZ")
d <- subset(d, datasetID !="chen15" | entered.by != "TA")

d <- subset(d, datasetID !="chichizola18" | entered.by != "TA") #entered by two people---but different figures/tables
d <- subset(d, datasetID !="han10" | entered.by != "CRD")
d <- subset(d, datasetID !="lee21" | entered.by != "AZ") #entered by two people---but different figures/tables
d <- subset(d, datasetID !="moeini21" | entered.by != "MN")
d <- subset(d, datasetID !="tilki07" | entered.by != "MN") #entered by two people---but different figures/tables
d <- subset(d, datasetID !="wytsalucy21" | entered.by != "DK")
d <- subset(d, datasetID !="yusefi-tanha19" | entered.by != "JS")

```

**Comment by lizzieinvancouver** [comment]
Let's fix this code, but then close this and work on issues #27  and #58 ...

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I looked into this. You are correct that there is an issue with that line of code, that I fixed using a which statement. But the missingData.csv also had +30000 lines of empty values. I went in like I did for JS's file and removed them. 

I updated the notes/egretScraping document with this as well.

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Nice! Please close this. 

Also, I updated the data/_README.md and added one relevant file from google drive.
