### ISSUE TITLE
file 108genspeclist needs help

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#56]
@ngoj1 It looks like you built [108genspeclist.csv](https://github.com/lizzieinvancouver/egret/commit/ae0b2e11028523bea4e9485cacc283b68db2dc0f#diff-231892f45a29e9ff636323d4076ba2b01e1a1cf6bcccee2e611bb310214d5352) but I see no R code where it was built and it's just hanging out in an analyses folder when it needs to be either:

- Clearly built in an R script (and then goes in analyses/output)
- Clearly something you got somewhere (then it goes in data/ and maybe analyses/input) with a README.

Can you explain this file so we can find it a new home? Happy to discuss today. Thanks!

**Comment by lizzieinvancouver** [comment]
Ditto for alternatingTempPaperList.xlsx

**Comment by ngoj1** [comment]
Code has now been written! The .csv file has just the list of papers while the excel file was what I used when I went through each paper one at a time to figure out their photoperiod, day/night order, and alternating temperature regime so it has thus been named alternatingTempsPaperList_withNotes.xlsx as it retains all of my findings.

**Comment by ngoj1** [comment]
Email logs from today 16 July 2024 regarding the reference assistance form.

![Rachael_16July2024_1](https://github.com/user-attachments/assets/2038911b-1c85-4b2e-b1a6-f8e7035303cf)
![Rachael_16July2024_2](https://github.com/user-attachments/assets/6d0e3d19-d14c-4e25-983e-0e1a1811e346)
![Rachael_16July2024_3](https://github.com/user-attachments/assets/138d2bdf-d0fd-44d7-8c0e-7ab448f6a3af)
