### ISSUE TITLE
fix mergedata ...

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#58]
@DeirdreLoughnan I got an error running your updated mergedata.R  -- because egret_FB and DB and XW were missing. I added them in, but I am still getting errors. Can you take a look when time allows? Thank you!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver this should be fixed.

But the full cleanall.R code is not currently running, there is an issue with the  [cleanPhotoperiod.R](https://github.com/lizzieinvancouver/egret/blob/main/analyses/cleaning/source/cleanPhotoperiod.R). 

@wangxm-forest when you have a chance, could you take a look at your code, there seems to be an issue with "morerowsmaybe" not being found. Is this just a placeholder or an object that needs to be created?

**Comment by lizzieinvancouver** [comment]
See also #49.

**Comment by wangxm-forest** [comment]
@DeirdreLoughnan I fixed the cleanPhotoperiod.R code. It should work for now.

**Comment by lizzieinvancouver** [comment]
This is working, but see #17
