### ISSUE TITLE
clean up the data folder 

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#59]
@wangxm-forest Can you work with @DeirdreLoughnan to clean up the data/ folder? It needs:

- [x] a `_README.md` file
- [x] ALL the egret data that is in analyses/input as .csv but only in .xlsx in data/ needs to be ALSO saved as .csv in the data/ folder (in case some day we cannot open the xlsx)
- [x] please put all the Egret scraping data in its own folder and give that folder a README
- [x] right now, a ton of the .csv files confuse me ... make the understandable and consistent (e.g., egret_JN.csv seems to be the main data, but egret_DM.csv seems to be a different tab from the xlsx).

**Comment by lizzieinvancouver** [comment]
And! Can you also put all the egret scraping files in analyses/input in their own folder? For example analyses/input/egretScraping ... and then update mergedata.R.

Once all this is done, assign this back to me to check. Thank you!

**Comment by lizzieinvancouver** [comment]
- [ ] rm useless folders and README inside personal folders with zero information

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I have cleaned the data and the input folders, let me know if there are any other changes you would like!

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Looks amazing! But a few more things:

- [ ] We should also move the all CSV files to the scrapedExcel folder. 
- [ ] Also it should egretScraping or scrapedEgret (as I see no reasons to only move the Excel)
- [ ] I prefer _README.md so it is at the top of my files, but we can discuss today if everyone is okay with that.
- [ ] The file types info in the data/README seems to refer only to files for scraping egret, right? If so, that info should only be in the data/scrapedNEWNAME/_README.md
- [ ] Double check that all files are explained in the data/README

Thanks!

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I have completed the additional cleaning we discussed

**Comment by lizzieinvancouver** [comment]
@DeirdreLoughnan Looks good. Please add an explanation of egret_fullsearch.xslx to the README and then you can close this.

**Comment by DeirdreLoughnan** [comment]
@lizzieinvancouver I have added a description of this file to the README.
