### ISSUE TITLE
mv addchill.R

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#60]
@dbuona I thought we came up with a new plan for this?

**Comment by lizzieinvancouver** [comment]
@dbuona Move to appropriate analyse folder.

**Comment by dbuona** [comment]
done! chilling now happens in the analysesSeedCues folder, sourced in the script seedcues_leadin.R

**Comment by lizzieinvancouver** [comment]
@dbuona Thanks! Friendly reminder that we're using camel case so I updated your names (and following OSPREE, leadin was RIGHT before running a model, this is cleaning to me, so renamed that). Can you add a _READMEcleaningSeedCues.md file with a quick overview of what the files do and close this after that?

**Comment by dbuona** [comment]
Done! Closing this issue now.
