### ISSUE TITLE
Summarize cleaning decisions and methods

### ISSUE THREAD

**Issue by DeirdreLoughnan** [lizzieinvancouver/egret#66]
@mention-group/all, I have started a document that summarizes the methods used to scrape data and some of the decisions made to clean individual columns. It can be found here: [egret/notes/egretDataScraping](https://github.com/lizzieinvancouver/egret/tree/main/notes).

While I have gone through the various git issues and highlighted the key decisions that we made while cleaning the data, it would be useful for everyone to read the cleaning sections pertaining to the columns they cleaned and let me know if there are any major decisions or assumption that were made, but not mentioned or referenced. 

@dbuona and @FrederikBaumgarten could you also write up a section on how the USDA data was cleaned?

**Comment by christophe-rd** [comment]
Hi @DeirdreLoughnan. I added my comments mostly for cleancoordinates. Thank you so much for your work on this!
