### ISSUE TITLE
update how we clean species names

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#69]
I just noticed we're using the package taxize to clean species names, but taxize is pretty outdated. I thought the new one was TaxonStand, but that is now outdated too! However, taxonstand points to [WorldFlora](https://cran.r-project.org/web/packages/WorldFlora/index.html), which I have confirmed is what we should use. Tell your friends (@dbuona @DeirdreLoughnan @christophe-rd @FrederikBaumgarten)!

@wangxm-forest Can you update the code to use WorldFlora instead of taxize? Apologies that I did not catch this sooner.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
I checked the names using WorldFlora, and got 56 different names, and this name is only 26 when using taxize.
I looked into those species names specifically picked by WorldFlora and searched on POWO. It seems that WorldFlora got the currently accepted species name for those species. To my understanding, taxize uses different references and picks the one name with the highest score (appears in most of the reference sources). Even though WorldFlora is one of its reference, maybe the species name hasn't been updated in other reference resources, so it fails to detect it.

In this case, I think maybe we can use WorldFlora instead unless you think POWO is also not reliable enough.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest pointed out yesterday that taxize uses Worldflora as a source; @lizzieinvancouver pointed out that https://cran.r-project.org/web/packages/taxize/index.html says taxize is ORPHANED as a maintainer even though it was just updated, WorldFlora https://cran.r-project.org/web/packages/WorldFlora/index.html seems maintained (also Lizzie misread, it yesterday; the plantlist is not updated; but WorldFlora is ... "The World Flora Online Taxonomic Backbone is an updated version of The Plant List (<http://www.theplantlist.org/>), a working list of plant names that has become static since 2013.")

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Thanks for your work on this!

> I looked into those species names specifically picked by WorldFlora and searched on POWO. It seems that WorldFlora got the currently accepted species name for those species

I think we should use WorldFlora. It's the best resource based on plant people that I trust and taxize is just the ROpenSci guys pulling resources and trying to rank them without knowing the sources ... so let's use WorldFlora. 

> To my understanding, taxize uses different references and picks the one name with the highest score (appears in most of the reference sources). 

Interesting! This must explain an issue I found with it a couple years ago visiting Nacho... we found that you could get different answer if you re-run it, which now I think could be a tie-break issue or such.

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
It's done! I've updated all the names according to WorldFlora.

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Nice! Would @dbuona or @DeirdreLoughnan be willing to check cleanspecies.R as an extra code review (see also issue #71)?

**Comment by lizzieinvancouver** [comment]
@dbuona @DeirdreLoughnan I started on this code review and finish it shortly! So please ignore my request above.

**Comment by lizzieinvancouver** [comment]
Code looks very nice, but needs the following changes:

- [ ] make the file name camelcase.
- [ ] make a flag to run the worldflora or not ... example below ...
- [ ] delete the taxize code 
- [ ] make comments slightly more specific ... so Fix becomes 'Fix species names that World Flora flagged'
- [ ] use setwd() with ifelse statement so everyone can use the list
- [ ] add classification.csv to repo .... add it to data/ and then also to input/
- [ ] update README in the data folder ... see if you can rm any of the taxonomy files, if not I would add them ALL to a folder called taxonomy/

Actually, I am not sure those files are explained in readme yet. Maybe @DeirdreLoughnan can tell us what they are used for as they're in her commit (https://github.com/lizzieinvancouver/egret/commit/f8a59ac95b5600e7bb8633d061235f8a3c11ce55). Thanks!

Example of a flag: 
```
runworldflora <- TRUE

if(runworldflora){
library("taxize")
library("stringr")
library("WorldFlora")
}

# Remove trailing spaces:
d$species <- tolower(d$species)
d$genus <- str_trim(d$genus)
d$species <- str_trim(d$species)
```

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 

I encountered an issue trying to upload the classification.csv file, as it exceeds 900 MB so I couldn't upload it regularly to GitHub. I found that maybe I can use Git Large File Storage (LFS) to upload it, but I'm not sure if it's the best option. Do you have any thoughts on this?

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Ah! Let's not upload it then (and I don't think that LFS is worth it). Instead please add a file called classificationcsvREADME to where the file should be noted when you downloaded it, from where, and why we're not uploading it. Thanks!

**Comment by wangxm-forest** [comment]
@lizzieinvancouver 
Just added a README file!

**Comment by lizzieinvancouver** [comment]
@wangxm-forest Great! Let me know when all the changes are done and I will check the file again.

**Comment by lizzieinvancouver** [comment]
This code is done! I checked it. The three unchecked tasks we decided not to do.
