### ISSUE TITLE
logistical/methods tasks for EGRET retreat

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#7]
These may need their own issues ... 

- [ ] Enter our papers!
- [ ] Ask questions about entering our papers
- [ ] Work on pinned questions about how to do data entry @DeirdreLoughnan leads
- [ ] WhereDataCodeLive session
- [ ] Work up methods so far 
- [ ] Come up with some names for tree ring capture device

**Comment by DeirdreLoughnan** [comment]
I created a [Wiki for seed propagation resources](https://github.com/lizzieinvancouver/egret/wiki/Seed-propagation-resources). I added the ones @dbuona found today, but if anyone finds additional ones, please add them.

**Comment by lizzieinvancouver** [comment]
Closing as this is +1 retreat ago.
