### ISSUE TITLE
check ResponseVar.R

### ISSUE THREAD

**Issue by dbuona** [lizzieinvancouver/egret#72]
line 227 seems most problematic, ie how many rows have error.

**Comment by DeirdreLoughnan** [comment]
@dbuona @lizzieinvancouver 

I took a look at this and have updated my code. Now on line 228 I remove all the rows that have "NA" for resp.error (n =1 9155), which leaves 11782 rows that do have a value for the error (although some cleaning is still needed, some are ranges), which is 38% of the total dataset (nTotal = 30937).
