### ISSUE TITLE
Visualize individual papers

### ISSUE THREAD

**Issue by lizzieinvancouver** [lizzieinvancouver/egret#8]
Pick 1-3 papers (ideally species that overlap with OSPREE) and visualize the studies within the papers in whatever way you think is best ... 

**Be sure to grab the PDF of the paper and check how data entry went!**

**Comment by lizzieinvancouver** [comment]
We picked 8 studies, that represent 8 OSPREE species (sad news: we only have maybe 20 overlapping species, but that should make the first paper easier to write!) ... everyone should visualize all 8 studies, but please pick TWO where you check the data entry on those studies. Here's the [link to the file](https://github.com/lizzieinvancouver/egret/blob/main/analyses/output/ospree8studies.csv)

First come, first serve -- announce here which two papers you will check the data entry on.

**Comment by lizzieinvancouver** [comment]
I pick muller03 and pipinis12 !

**Comment by DeirdreLoughnan** [comment]
I pick ahola99 and javanmard14!

**Comment by lizzieinvancouver** [comment]
I think muller03 looks okay (I found and added the PDF to the drive). I think pipinis is entered okay, but the germination year would be 2009 sometimes (they were collected in early October 2008 with some storage of up to 6 months) though this seems a small issue. But I wanted to check on how the chill duration was entered, like this:

`60 days (warm) + 120 days (cold)`

and the germ.temp...

`20°C (6h dark) + 25°C (18h light) `

Is that okay?

**Comment by DeirdreLoughnan** [comment]
I found some issues with my two papers:

Ahola99:

- Missing information from the site --- missing lat/long, source population, and continent --- but is in pdf
- Chill duration for control (no chilling) is NA, but should be 0
- Missing year of experiment, 1996
- Missing information about seed storage discussed in pdf
- Infrared light entered as the chemical concentration

Javanmard14:

No information about the seed washing treatment 
Only fig 3 scraped (cold strat vs GA3), but Fig 2 should maybe be scraped as well (washing treatment vs cold stratification). Figure 1 is for the washing treatment vs GA3, so I think we could skip it.

**Comment by lizzieinvancouver** [comment]
Done. See also #28 and #48 ... which should also have some of individual paper plots.
